name: Docker CI
as
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend ./frontend

      - name: Build backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-backend ./backend

      - name: Build admin
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-admin ./admin

      - name: Push frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend

      - name: Push backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-backend

      - name: Push admin
        run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-admin